apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-aws.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hello-aws.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-aws.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hello-aws.name" . }}
    spec:
      containers:
        - name: hello
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-listen=:{{ .Values.service.targetPort }}"
            - "-text={{ .Values.message }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

