replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: "1.0"
  pullPolicy: IfNotPresent

message: "hello from AWS - eu-central-1"

service:
  port: 80
  targetPort: 5678

ingress:
  enabled: true
  host: hello-eu.aws-dvirlabs.com
  scheme: internet-facing
  targetType: ip
  # optional: keep name short (<=32 chars) if you enable it
  loadBalancerName: hello-eu

